---
title: "simple_workflow_Sisal"
author:
  - name: "Socorro Dominguez Vidaña"
    correspondence: false
    email: dominguezvid@wisc.edu
    orcid_id: 0000-0002-7926-4935
institute:
  - uwiscgeog:
    name: "University of Wisconsin -- Madison: Department of Geography"
date: "`r Sys.Date()`"
always_allow_html: true
output:
  html_document
---

```{r setup, echo=FALSE}
options(warn = -1)
pacman::p_load(neotoma2, dplyr, ggplot2, sf, geojsonsf, leaflet, flextable, readr, stringr, tidyr, patchwork)
```

Exercises executed in March 2025 in the simple workflow. 

```{r boundingBox}
geoJSON <- '{"type": "Polygon",
        "coordinates": [[
            [-7.030,  36.011],
            [-18.807, 23.537],
            [-19.247, 10.282],
            [-9.139,  -0.211],
            [18.370, -37.546],
            [35.069, -36.352],
            [49.571, -27.097],
            [58.185,   0.755],
            [53.351,  13.807],
            [43.946,  12.008],
            [31.202,  33.629],
            [18.897,  34.648],
            [12.393,  35.583],
            [11.075,  38.184],
            [-7.030,  36.011]
          ]
        ]}'

africa_sf <- geojsonsf::geojson_sf(geoJSON)

# Note here we use the `all_data` flag to capture all the sites within the polygon.
# We're using `all_data` here because we know that the site information is relatively small
# for Africa. If we were working in a new area or with a new search we would limit the
# search size.
africa_sites <- neotoma2::get_sites(loc = africa_sf, all_data = FALSE)
africa_sites
```


```{r datasetsFromSitesResult, message=FALSE}
africa_datasets <- neotoma2::get_datasets(loc = africa_sf, all_data = TRUE)

datasets(africa_datasets) %>% 
  as.data.frame() %>% 
  head()
```


```{r downloadsCode}
africa_speleothem <- africa_datasets %>% 
  neotoma2::filter(datasettype == 'speleothem')

neotoma2::summary(africa_speleothem) %>% 
  head()
```

```{r taxaCode}
africa_dl <- africa_speleothem %>% get_downloads() 

as.data.frame(africa_dl) %>% 
  head()
```

```{r add_entityCode}
africa_sp <- get_speleothems(africa_dl)
africa_sp
```

```{r samp_w_entityCode}
samp_w_entity <- speleothems(africa_sp)
samp_w_entity
```



```{r taxa2Code, message=FALSE}
type_of_data <- taxa

neotomatx <- africa_dl %>% type_of_data()
neotomatx %>% 
  head()
```